[package]
name = "quest-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3-sys = "0.5.5"
halcyon = { path = "halcyon" }
rectpack2d-rs = { path = "rectpack2d-rs" }

# [target.release]
# strip = true
# lto = true
# panic = "abort"
# codegen-units = 1
